app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use App\Profile;
use App\User;

Route::get('/', function () {
    $users = \App\Consultant::get();
    $profiles = Profile::all();
//dd($users);

    // dd($users);
    return view('users-mgmt/index',['users'=>$users]);
});



Route::get('/downloadPDF/download','ProfileController@downloadPDF');
Route::get('/downloadPDF/{id}','ProfileController@downloadPDF');

//Route::put('/bookings', 'API\UserController@putUpdateUser');
Route::resource('profile','ProfileController');
Route::resource('consultant','ConsultantController');
Route::resource('consultants','ConsultantController@index');
Route::resource('/consultant/show','ConsultantController@store');
//Route::resource('/consultant','UserController@store');
Route::post('/consultantsd','ConsultantController@doLogin')->name('doLogin');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );




Route::auth();

Route::get('/home', 'HomeController@index');

resources/views/users-mgmt/base.blade.php
@extends('layouts.app')

@section('content')

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Consultant
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
        <li class="active">Consultant</li>
      </ol>
    </section>
    @yield('action-content')
    <!-- /.content -->
  </div>
@endsection

resources/views/users-mgmt/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Add New Consultant</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST"
                              action="{{ route('consultant.store') }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}" style="">
                                <label for="name" class="col-md-4 control-label">Full Names<a
                                            class="text-red">*</a></label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name"
                                           value="{{ old('name') }}">

                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="email" class="col-md-4 control-label">E-Mail Address<a
                                            class="text-red">*</a></label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control" name="email"
                                           value="{{ old('email') }}" required>

                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>


                            <div class="form-group{{ $errors->has('ref') ? ' has-error' : '' }}">
                                <label for="ref" class="col-md-4 control-label">Reference Number<a
                                            class="text-red">*</a></label>

                                <div class="col-md-6">
                                    <input id="ref" type="ref" class="form-control" name="ref" required>

                                    @if ($errors->has('ref'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('ref') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group">


                                <div class="col-md-6">
                                    <input id="code" type="hidden" class="form-control" name="code" required>

                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Create Consultant
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users-mgmt/edit.blade.php
@extends('users-mgmt.base')

@section('action-content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Update Arranger</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('user-management.update', ['id' => $user->id]) }}">
                        <input type="hidden" name="_method" value="PATCH">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
                            <label for="username" class="col-md-4 control-label">Arranger Name</label>

                            <div class="col-md-6">
                                <input id="username" type="text" class="form-control" name="username" value="{{ $user->username }}" required autofocus>

                                @if ($errors->has('username'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('username') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                            <label for="firstname" class="col-md-4 control-label">First Name</label>

                            <div class="col-md-6">
                                <input id="firstname" type="text" class="form-control" name="firstname" value="{{ $user->firstname }}" required>

                                @if ($errors->has('firstname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                            <label for="lastname" class="col-md-4 control-label">Last Name</label>

                            <div class="col-md-6">
                                <input id="lastname" type="text" class="form-control" name="lastname" value="{{ $user->lastname }}" required>

                                @if ($errors->has('lastname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                       {{--  <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">New Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password">

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation">
                            </div>
                        </div>
                        --}}


                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users-mgmt/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row"></div>

        @if(isset(Auth::user()->email))
            <script>window.location="/profile";</script>
        @endif


        <form class="form-horizontal" id="sample_form"   role="form" method="POST" action="{{ route('doLogin') }}">
            {{ csrf_field() }}
        <div class="col-sm-7" id="background">
            <img src="{{url('/images/4036fd1bf88ed153a250f46a05d64ecd.jpg')}}" alt="Image" class="img-responsive">
        </div>
<?php //echo Carbon\Carbon::now() . "\n";
?>
        <div class="col-sm-4 booking" >
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-8">
                    <img src="{{url('/images/download.png')}}" alt="logo" class="img-responsive"><br><br>

                </div>
                <div class="col-sm-2"></div>
            </div>
            <div class="form-group" hidden="hidden" id="cons_name">
                <select class="form-control " name="cons_name" id="cons_name" required>
                    @foreach ($users as $user)
                        <option value="{{$user->name}}">{{$user->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group"  id="cons_email">
                <select class="form-control " name="cons_email" id="cons_email" required>
                    <option value="">Select Consultant</option>
                @foreach ($users as $user)
                        <option value="{{$user->email}}">{{$user->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group{{ $errors->has('cons_ref') ? ' has-error' : '' }}">

                    <input id="cons_ref" type="text" class="form-control" name="cons_ref" placeholder="Reference" required>

                    @if ($errors->has('cons_ref'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('cons_ref') }}</strong>
                                    </span>
                    @endif
            </div>
                <div class="wrapper">
                <button class="btn btn-info"  type="submit" >Create Profile Link</button>
                    <br>
                    <br>
                </div>
            <?php //dd($user);?>





                <div class="col-sm-offset-3"><div class="wrapper" id="last_inserted_id"></div></div>
            <div class="col-sm-1 ">

            </div>

        </div>
        </form>
    </div>
    <script>

        $(document).on('submit', '#sample_form', function(event) {

            event.preventDefault();
            var form_contents = $(this).serialize();

            $.post("{{ route('doLogin') }}", form_contents, function (data) {

                $('#sample_form')[0].reset();
                $('#last_inserted_id').html('  <?php echo $_SERVER['HTTP_HOST']; ?>/profile/' + data.id + '/edit');
            }, 'json');
           // $_SERVER['REQUEST_URI'] .'://' . $_SERVER['HTTP_HOST']; ?>/profile/' + data.id + '/edit'

        });
    </script>



@endsection

resources/views/users-mgmt/show.blade.php
@extends('layouts.app')

@section('content')
    <!-- Main content -->
    <section class="content">
        <div class="box">
            <div class="box-header">
                <div class="row">
                    <div class="col-sm-8">
                        <h3 class="box-title">List Of Consultants</h3>
                    </div>
                    <div class="col-sm-4">
                        <a class="btn btn-primary" href="{{ route('consultant.create') }}">Create new Consultant</a>
                    </div>
                </div>
            </div>
            <!-- /.box-header -->
            @if (Session::has('message'))
                <div class="alert alert-info">{{ Session::get('message') }}</div>
            @endif

            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <td>Consultant Name</td>
                    <td>Email</td>
                    <td>Reference</td>
                    <td>Code</td>
                    <td>Actions</td>
                </tr>
                </thead>
                <tbody>

                @foreach($users as $key => $value)

                    <tr>
                        <td>{{ $value->name }}</td>
                        <td>{{ $value->email }}</td>
                        <td> {{$value->ref }}</td>
                        <td> {{$value->code }}</td>
                        <!-- we will also add show, edit, and delete buttons -->
                        <td>

                            <!-- delete the nerd (uses the destroy method DESTROY /nerds/{id} -->
                            <!-- we will add this later since its a little more complicated than the other two buttons -->

                            <!-- show the nerd (uses the show method found at GET /nerds/{id} -->
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">

                            <a href="{{ route('consultant.destroy', ['id' => $value->id]) }}" class="btn btn-danger col-sm-3 col-xs-5 btn-margin">
                                Remove Consultant
                            </a>
                            <!-- edit this nerd (uses the edit method found at GET /nerds/{id}/edit -->

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </section>
    <!-- /.content -->
@endsection